# Generated by Django 4.2.6 on 2023-10-31 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagebilling',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='taskbilling',
            name='billing_unit',
            field=models.CharField(choices=[('pallet', 'Pallet'), ('box', 'Box'), ('weight', 'Weight'), ('manual', 'Manual')], max_length=10),
        ),
        migrations.AlterField(
            model_name='taskbilling',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
