# Generated by Django 4.2.6 on 2023-10-26 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_contact_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='account_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
