# Generated by Django 4.2.6 on 2023-11-07 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_alter_bank_created_by_alter_carrier_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='ein',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.CreateModel(
            name='CustomerAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='partners.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ConsigneeAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('consignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='partners.consignee')),
            ],
        ),
        migrations.CreateModel(
            name='CarrierAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='partners.carrier')),
            ],
        ),
    ]
