# Generated by Django 4.2.6 on 2023-10-27 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('number', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SequenceNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packging_unit_number', models.PositiveIntegerField(default=1)),
                ('pallet_number', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='PackagingUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('number', models.PositiveIntegerField(default=1)),
                ('unit_type', models.CharField(choices=[('box', 'Box'), ('pack', 'Pack'), ('each', 'Each')], max_length=50)),
                ('pallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handling_units.pallet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
