# Generated by Django 4.2.6 on 2023-10-27 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SequenceNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packging_unit_number', models.PositiveIntegerField(default=1)),
                ('pallet_number', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
