# Generated by Django 4.2.6 on 2023-10-31 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('sequence_number', models.IntegerField(default=1)),
                ('billing_unit', models.CharField(max_length=50)),
                ('level', models.PositiveIntegerField(default=0, editable=False)),
            ],
            options={
                'ordering': ['level', 'sequence_number'],
            },
        ),
    ]
