# Generated by Django 4.2.6 on 2023-10-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='sequence_number',
            field=models.IntegerField(default=1),
        ),
    ]
