# Generated by Django 4.2.6 on 2023-10-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_category_sequence_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='sequence_number',
            field=models.IntegerField(default=1),
        ),
    ]
