# Generated by Django 4.2.6 on 2023-10-31 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventories', '0001_initial'),
        ('operations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partners', '0001_initial'),
        ('handling_units', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='inbound',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operations.inbound'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventories.inventory'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='outbound',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operations.outbound'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operations.transfer'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventory',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='partners.customer'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='inbound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.inbound'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='pallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handling_units.pallet'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operations.transfer'),
        ),
    ]
