# Generated by Django 4.2.6 on 2023-10-31 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(editable=False, max_length=50, unique=True)),
                ('packer', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('identification_code', models.CharField(max_length=100)),
                ('memo', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='categories.category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
