# Generated by Django 4.2.6 on 2023-10-29 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0005_deliveryaddress_delete_carrieraddress'),
        ('products', '0002_alter_product_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='partners.customer'),
        ),
    ]
